CREATE TABLE EMPLOYEES (
	EMP_ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(15) NOT NULL,
	LAST_NAME VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(128) NOT NULL,
  DEP_ID BIGINT NOT NULL,
	CONSTRAINT CONSTRAINT_EMPLOYEES PRIMARY KEY (EMP_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_EMPLOYEES ON EMPLOYEES (EMP_ID);

CREATE TABLE DEPARTMENT (
	DEP_ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
	DEP_NAME VARCHAR(20) NOT NULL,
	DEP_LOCATION VARCHAR(15) NOT NULL,
	CONSTRAINT CONSTRAINT_DEPARTMENT PRIMARY KEY (DEP_ID)
);
CREATE INDEX PRIMARY_KEY_DEPARTMENT ON EMPLOYEES (DEP_ID);

